name: GA Project

on:
# Force deployment, push on main and push on pull_request
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      types:
        - opened
      branches:
        - main

# permissions:

concurrency:
# group: 
  cancel-in-progress: true

jobs:
  test:



  build:



  deploy: