name: GA Project

on:
# Force deployment, push on main and push on pull_request
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      types:
        - opened
      branches:
        - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
# group: 
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ">=18.0"
          cache: "npm"

      - name: Install dependecies
        run: npm ci

      - name: Run the linters
        run: npm test

      - name: Run all scripts
        run: script/url-checker.js
        env: 
          URL_CHECKER_TIMEOUT: ${{ vars.URL_CHECKER_TIMEOUT }}

  build:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup pages
        uses: actions/configure-pages@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ">=18.0"
          cache: "npm"
        
      - name: Install dependencies
        run: npm ci

      - name: Build site
        env: 
          PATH_PREFIX: /${{ github.event.repository.name }}/
        run: npm run eleventy_prod

      - name: Upload the contents
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest

    steps:
      - name: Download build site
        uses: actions/download-artifact@v8
        with:
          path: "_site"

      - name: Add issue
        run: |
          gh auth login --with-token <<<"${{ secrets.GITHUB_TOKEN }}"

          gh issue create --title "$(date) - Deployment: ${{ outputs.deployment }}"

          gh issue comment ${{ github.event.issue.number }} \
          --body-file ${{ URL }}
